// For now the app is in Dutch because the recipes are in Dutch. Sorry peeps :)
export enum Localisation {
    PREVIOUS_RECIPE = "Naar vorig recept",
    NEXT_RECIPE = "Naar volgend recept",
    INGREDIENT = "Ingrediënt",
    INGREDIENTS = "Ingrediënten",
    STEPS = "Instructies",
    STEP = "Instructie",
    WELCOME = "Welkom",
    NINJA = "Ninja",
    NOT_YOU = "Ben jij dit niet?",
    LOGIN_FOR_MORE_FEATURES = "Log in via Github en ontgrendel meer.",
    LOGGED_IN_ENCOURAGING = "Ingelogd? Goed bezig.",
    LOG_OUT = 'Toch liever ninja? Log uit.',
    ADD_OWN_RECIPE = 'Eigen recept toevoegen',
    ADD_RECIPE = 'Recept toevoegen',
    ACCOUNT_MANAGEMENT = 'Account beheren',
    CANCEL = 'Annuleren',
    TITLE = 'Titel',
}